### ISSUE TITLE
merge sort in cpp

### ISSUE THREAD

**Issue by sauravjaiswalsj** [fnplus/interview-techdev-guide#13]

**Comment by aquibbaig** [comment]
Can I take this up?

**Comment by sauravjaiswalsj** [comment]
Yes @aquibbaig you can take up this.

**Comment by aquibbaig** [comment]
Hi, I would like to have a Pull request but the implementation has already been done?

**Comment by tush38** [comment]
@sauravjaiswalsj  can i work on this?
