### ISSUE TITLE
[Algorithm] Euclidean GCD [Python]

### ISSUE THREAD

**Issue by fmachado091** [fnplus/interview-techdev-guide#142]
Euclidean algorithm for calculating the greatest common divisor (GCD) of two natural numbers.

Reference: https://en.wikipedia.org/wiki/Euclidean_algorithm

**Comment by fmachado091** [comment]
Assigning it to me.

**Comment by Rahul-45** [comment]
Can i work on this?

**Comment by fmachado091** [comment]
https://github.com/fnplus/interview-techdev-guide/pull/143 closes this.
