### ISSUE TITLE
fibonacci series using java

### ISSUE THREAD

**Issue by vyom153069** [fnplus/interview-techdev-guide#179]

**Comment by ravivarmalearner** [comment]
can i take up this?

**Comment by shivang-chhabra** [comment]
can i resolve this issue?

**Comment by ravivarmalearner** [comment]
i already made pull request.

**Comment by jenistenxavier** [comment]
@shivang-chhabra : please explore other folders and issues. Feel free to create new issues. check out our contribution guidelines for reference

**Comment by jenistenxavier** [comment]
@ravivarmalearner : Can you pls comment the PR for reference
