### ISSUE TITLE
Algo Insertion Sort Java

### ISSUE THREAD

**Issue by shanky199912** [fnplus/interview-techdev-guide#195]
Here is the guide to Insertion Sort
https://www.tutorialspoint.com/data_structures_algorithms/insertion_sort_algorithm.htm

**Comment by WOLFI3654** [comment]
I'll take care of this one!

**Comment by jenistenxavier** [comment]
@WOLFI3654 : Thanks for contributing.
@shanky199912 : Please look for other open algorithms and submit PRs.
