### ISSUE TITLE
Sieve of Eratosthenes algorithm

### ISSUE THREAD

**Issue by NripeshKumar** [fnplus/interview-techdev-guide#239]
I want to do using C++

**Comment by anmolagarwal999** [comment]
Can I do this ?

**Comment by siddharthrajaraja** [comment]
May I do this please!!

**Comment by galihsatriawan** [comment]
I have tried it , please check it, thanks

**Comment by jenistenxavier** [comment]
@galihsatriawan : please share the PR for reference

**Comment by jenistenxavier** [comment]
Enhancements are very much appreciated. Feel free to add a folder if you wish to provide solution in a different language

**Comment by tush38** [comment]
@jenistenxavier  can i work on this?

**Comment by galihsatriawan** [comment]
This is the referenced #281

**Comment by NripeshKumar** [comment]
Implemented Sieve ofEratosthenes algorithm in Java
This is the reference #394
