### ISSUE TITLE
Check if a number is magic (Recursive sum of digits is 1)

### ISSUE THREAD

**Issue by rishabhsingh20** [fnplus/interview-techdev-guide#292]

**Comment by Ri2parna** [comment]
can i take this ?

**Comment by Ri2parna** [comment]
I have the python implementation of this.

**Comment by Ri2parna** [comment]
HI @rishabhsingh20  @jenistenxavier  . The python solution to magic number has been implemented and this solution can be merged.

**Comment by jenistenxavier** [comment]
@rishabhsingh20 : can you check all your commits and confirm if all the files are in the appropriate folders
