### ISSUE TITLE
[Algorithm] Selection Sort in Java

### ISSUE THREAD

**Issue by stnbnvdz** [fnplus/interview-techdev-guide#304]
Can I work on this?

## Information about my new algorithm

- **Algorithm Name:** Selection Sort

- **Programming Language:** Java

- **Time complexity:** O(n2)

**Comment by shanky199912** [comment]
The Selection sort algo in Java is already added. Try opening some other issue.

**Comment by stnbnvdz** [comment]
Please see my new issue about Heap Sort in Java. Thanks!
