### ISSUE TITLE
Selection sort algo in c++

### ISSUE THREAD

**Issue by snehalkumar5** [fnplus/interview-techdev-guide#329]
I wish to do this issue

**Comment by shivang-chhabra** [comment]
can i resolve it ?

**Comment by jenistenxavier** [comment]
@the-code-meister : File format need to be changed. 
Do not use .md for your algorithms

**Comment by busi-reddy-karnati** [comment]
Can I do this, please?

**Comment by kratikaatgithub** [comment]
Hi can I get assigned this issue as part of hactoberfest:
thanks

**Comment by jatinjain001** [comment]
I want to work on this please

**Comment by JIBIN-P** [comment]
assign me this issue.

**Comment by snehalkumar5** [comment]
This issue was resolved previously and i forgot to close it sorry. You can always find algos and open new issues tho :)
