### ISSUE TITLE
Algo Kruskal's Algorithm Java

### ISSUE THREAD

**Issue by shanky199912** [fnplus/interview-techdev-guide#355]
Here is the description of the algorithm of the Kruskal algorithm .
https://www.geeksforgeeks.org/kruskals-algorithm-simple-implementation-for-adjacency-matrix/

**Comment by shanky199912** [comment]
### Want to work on this issue
yes

**Comment by NripeshKumar** [comment]
i wan't to do using c++

**Comment by shanky199912** [comment]
Then plss open another issue for C++
