### ISSUE TITLE
[Algorithm] Magic Number [Java]

### ISSUE THREAD

**Issue by RiturajJain** [fnplus/interview-techdev-guide#409]
I want to contribute Java code for Magic Number problem (The Python code for this is already present in the repository).

**Comment by vyom153069** [comment]
Can i work on this?

**Comment by RiturajJain** [comment]
Hi @vyom153069, I have already submitted the PR for this. You can checkout other issues or submit your own issues.

**Comment by vyom153069** [comment]
@RiturajJain ,no problem
