### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by amirkaveh** [fnplus/interview-techdev-guide#418]
1. Update README.md tables based on current code status (implemented data structures and algorithms).

2. Correct inaccurate or wrong table links to Wikipedia pages:
+Circular Linked List
+Disjoint Sets
+Adjacency matrix
+Pre-Order Traversal
+Post-Order Traversal
+In-Order Traversal
+Height of the Tree
+Depth of the Tree

**Comment by ofemeteng** [comment]
Hi.
Can I work on this and is it okay to link to resources other than Wikipedia.
