### ISSUE TITLE
Binary Search Tree [python]

### ISSUE THREAD

**Issue by SubCoder1** [fnplus/interview-techdev-guide#435]
@sauravjaiswalsj I would like to work on this issue.

**Comment by sauravjaiswalsj** [comment]
Sure go ahead

**Comment by SubCoder1** [comment]
@sauravjaiswalsj my pull request was merged, why is this issue still open?

**Comment by sauravjaiswalsj** [comment]
Closing !!It is probably because you did not correctly mentioned your issue number in your pull request
