### ISSUE TITLE
[Algorithm] Longest Common Subsequence [Python]

### ISSUE THREAD

**Issue by pb-10** [fnplus/interview-techdev-guide#522]
Hey, I'd like to add the Longest Common Subsequence Algorithm in the Dynamic Programming Algorithm section.

**Comment by hash84** [comment]
I would like to work on this issue. Will try to raise a PR by today evening

**Comment by hash84** [comment]
Please review the pull request https://github.com/fnplus/interview-techdev-guide/pull/534
