### ISSUE TITLE
Linear Search in C

### ISSUE THREAD

**Issue by Vineet-Sharma29** [fnplus/interview-techdev-guide#56]
### Want to work on this issue?
Yes

**Comment by sauravjaiswalsj** [comment]
Sure you can

**Comment by divyhshah** [comment]
yes i want to work on this issue and i am able to provide efficient algorithm for linear search

**Comment by dheeraj-2000** [comment]
hey i want to add a small code of dfs in python

**Comment by divyhshah** [comment]
Send me message on github

On 06-Oct-2019 2:35 PM, Dheeraj Chaudhary <notifications@github.com> wrote:

hey i want to add a small code of dfs in python

**Comment by ravi9989** [comment]
can I work on this issue?

**Comment by Vineet-Sharma29** [comment]
@ravi9989 thanks for your interest in contributing for this issue. However it has been solved in C. You can check if it is not implemented in some other language and you can try solve it using that missing language.
