### ISSUE TITLE
Array & Linear Linked List Implementation of Queue

### ISSUE THREAD

**Issue by cherryWood55** [fnplus/interview-techdev-guide#84]
A queue is a data structure in which insertion and deletion take place from two different ends. It follows the First-in-First-Out (FIFO) principle. A queue can be implemented using an array based approach as well as a linked list based approach.

**Comment by aneesh98** [comment]
Can I work on this issue? Also which language to use for implementation?

**Comment by cherryWood55** [comment]
Yes sure! Go Ahead! You are free to use any language.

**Comment by SubCoder1** [comment]
@sauravjaiswalsj  Can I work on this issue?
