### ISSUE TITLE
Dynamic Array in Cpp

### ISSUE THREAD

**Issue by sauravjaiswalsj** [fnplus/interview-techdev-guide#9]

**Comment by Anish-Jay** [comment]
Updating this unassigned task.

**Comment by shivang-chhabra** [comment]
can i resolve this?

**Comment by dhruvhacks** [comment]
@jenistenxavier I think this issue should be closed since it has been merged/file exists! reference- [link](https://github.com/fnplus/interview-techdev-guide/blob/master/Data%20Structures/Dynamic%20Array/CPP/dynamic_array.cpp)

**Comment by jenistenxavier** [comment]
@dhruvhacks : sure. thanks.
