### ISSUE TITLE
Queue in Python

### ISSUE THREAD

**Issue by AkashM398** [fnplus/interview-techdev-guide#94]
**I would like to Implement Queue Data Structure in Python**

**Comment by SubCoder1** [comment]
@sauravjaiswalsj  I would like to work on this issue.

**Comment by jenistenxavier** [comment]
@AkashM398 We are unable to merge your PR as there are conflicts
Can you check it and make sure the conflict is resolved
Thanks

**Comment by SubCoder1** [comment]
#385

**Comment by SubCoder1** [comment]
@sauravjaiswalsj  @jenistenxavier Added a pull request for this issue I was assigned to, #385
